// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/emails.proto

package emails

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	TemplateId           string   `protobuf:"bytes,3,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	TemplateData         []byte   `protobuf:"bytes,4,opt,name=template_data,json=templateData,proto3" json:"template_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e333a7bdf85cf1c, []int{0}
}

func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (m *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(m, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

func (m *SendRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SendRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *SendRequest) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *SendRequest) GetTemplateData() []byte {
	if m != nil {
		return m.TemplateData
	}
	return nil
}

type SendResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResponse) Reset()         { *m = SendResponse{} }
func (m *SendResponse) String() string { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()    {}
func (*SendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e333a7bdf85cf1c, []int{1}
}

func (m *SendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResponse.Unmarshal(m, b)
}
func (m *SendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResponse.Marshal(b, m, deterministic)
}
func (m *SendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResponse.Merge(m, src)
}
func (m *SendResponse) XXX_Size() int {
	return xxx_messageInfo_SendResponse.Size(m)
}
func (m *SendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SendRequest)(nil), "emails.SendRequest")
	proto.RegisterType((*SendResponse)(nil), "emails.SendResponse")
}

func init() {
	proto.RegisterFile("proto/emails.proto", fileDescriptor_3e333a7bdf85cf1c)
}

var fileDescriptor_3e333a7bdf85cf1c = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xcd, 0x4d, 0xcc, 0xcc, 0x29, 0xd6, 0x03, 0x73, 0x84, 0xd8, 0x20, 0x3c, 0xa5,
	0x72, 0x2e, 0xee, 0xe0, 0xd4, 0xbc, 0x94, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x21,
	0x2e, 0x96, 0xb4, 0xa2, 0xfc, 0x5c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x88,
	0x8f, 0x8b, 0xa9, 0x24, 0x5f, 0x82, 0x09, 0x2c, 0x02, 0x64, 0x09, 0xc9, 0x73, 0x71, 0x97, 0xa4,
	0xe6, 0x16, 0xe4, 0x24, 0x96, 0xa4, 0xc6, 0x67, 0xa6, 0x48, 0x30, 0x83, 0x25, 0xb8, 0x60, 0x42,
	0x9e, 0x29, 0x42, 0xca, 0x5c, 0xbc, 0x70, 0x05, 0x29, 0x89, 0x25, 0x89, 0x12, 0x2c, 0x40, 0x25,
	0x3c, 0x41, 0x3c, 0x30, 0x41, 0x17, 0xa0, 0x98, 0x12, 0x1f, 0x17, 0x0f, 0xc4, 0xe2, 0xe2, 0x82,
	0xfc, 0xbc, 0xe2, 0x54, 0x23, 0x5b, 0x2e, 0x36, 0x57, 0xb0, 0x93, 0x84, 0x8c, 0xb9, 0x58, 0x40,
	0x32, 0x42, 0xc2, 0x7a, 0x50, 0x17, 0x23, 0x39, 0x50, 0x4a, 0x04, 0x55, 0x10, 0xa2, 0x59, 0x89,
	0xc1, 0x89, 0x2f, 0x8a, 0x07, 0xec, 0x31, 0x6b, 0x88, 0x74, 0x12, 0x1b, 0x98, 0x67, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x16, 0xc0, 0xfd, 0x5b, 0xfc, 0x00, 0x00, 0x00,
}
