// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/emails.proto

package emails

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Emails service

func NewEmailsEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Emails service

type EmailsService interface {
	Send(ctx context.Context, in *SendRequest, opts ...client.CallOption) (*SendResponse, error)
}

type emailsService struct {
	c    client.Client
	name string
}

func NewEmailsService(name string, c client.Client) EmailsService {
	return &emailsService{
		c:    c,
		name: name,
	}
}

func (c *emailsService) Send(ctx context.Context, in *SendRequest, opts ...client.CallOption) (*SendResponse, error) {
	req := c.c.NewRequest(c.name, "Emails.Send", in)
	out := new(SendResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Emails service

type EmailsHandler interface {
	Send(context.Context, *SendRequest, *SendResponse) error
}

func RegisterEmailsHandler(s server.Server, hdlr EmailsHandler, opts ...server.HandlerOption) error {
	type emails interface {
		Send(ctx context.Context, in *SendRequest, out *SendResponse) error
	}
	type Emails struct {
		emails
	}
	h := &emailsHandler{hdlr}
	return s.Handle(s.NewHandler(&Emails{h}, opts...))
}

type emailsHandler struct {
	EmailsHandler
}

func (h *emailsHandler) Send(ctx context.Context, in *SendRequest, out *SendResponse) error {
	return h.EmailsHandler.Send(ctx, in, out)
}
